#!/bin/sh

set -e

fname=$(echo $1 | cut -f 1 -d '.')
shift 1
echo "Compiling ${fname}.v..."

if [ -d "${fname}_target" ]
then
    rm -rf "${fname}_target"
fi
if [ -f "${fname}_target" ]
then
    >&2 echo "Target dir is a file!!"
    exit 1
fi
mkdir "${fname}_target"

echo "Running yosys..."
yosys \
    -p "read_verilog ${fname}.v; synth_gowin -json ${fname}_target/${fname}.json" \
    $@ \
    > "${fname}_target/yosys.log"

echo "Running nextpnr..."
export LD_LIBRARY_PATH=/home/apicula/.pyenv/versions/3.12.3/lib
    nextpnr-himbaechel \
    --json "${fname}_target/${fname}.json" \
    --write "${fname}_target/pnr_${fname}.json" \
    --device "GW1NR-LV9QN88PC6/I5" \
    --vopt family=GW1N-9C \
    --vopt cst=tangnano9k.cst \
    2>&1 \
    | cat > "${fname}_target/nextpnr.log"

if [ ! -f "${fname}_target/pnr_${fname}.json" ]
then
    echo "Nextpnr failed, check \"${fname}_target/nextpnr.log\" for more details."
    exit 1
fi

echo "Running gowin_pack..."
/home/apicula/.pyenv/shims/gowin_pack \
    -d GW1N-9C \
    -o "${fname}_target/pack.fs" \
    "${fname}_target/pnr_${fname}.json"

echo "Done!"